language: node_js

os:
  - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

node_js:
  - 4.0

before_install:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export CXX=g++-4.8; fi
  - $CXX --version

before_script:
  - wget https://s3.amazonaws.com/bitly-downloads/nsq/nsq-0.3.5.linux-amd64.go1.4.2.tar.gz -O /tmp/nsq.tar.gz
  - tar -xvf /tmp/nsq.tar.gz
  - export PATH=$PATH:$PWD/nsq-0.3.5.linux-amd64.go1.4.2/bin/
  - ./bin/start-nsq.sh
